name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: build and test on Ubuntu
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: mkdir
      run: mkdir -p bin/Debug/; mkdir -p obj/Debug/
    - name: make
      run: make
    - name: make check
      run: make check
    - uses: actions/upload-artifact@v2
      with:
        name: hcc
        path: bin/Debug/hcc
